from pydantic import BaseModel, Field
from typing import List, Optional

class ChatQuery(BaseModel):
    """Data transfer object for chat queries."""
    question: str = Field(..., 
                      title="User question",
                      description="The question to ask the RAG system",
                      min_length=1)

class ChatResponse(BaseModel):
    """Data transfer object for chat responses."""
    answer: str = Field(..., 
                    title="Generated answer",
                    description="The answer generated by the model")
    retrieved_context: List[str] = Field(default_factory=list,
                                    title="Retrieved context", 
                                    description="The context chunks retrieved from the vector database")
